services:
  cassandra:
    container_name: exemple-cassandra
    image: cassandra:4.1.5
    networks:
    - test
    environment:
    - HEAP_NEWSIZE=1M
    - MAX_HEAP_SIZE=512m
    - "JVM_OPTS=-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.initial_token=0"
    ports:
    - 9042:9042
    volumes:
    - ./resources/cassandra:/usr/local/tmp/cassandra
    - ./conf/cassandra:/usr/local/etc/cassandra
    - ./data/cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "sh", "/usr/local/etc/cassandra/healthcheck_cassandra.sh"]
      interval: 10s
      retries: 10
      start_period: 30s
  zookeeper:
    container_name: exemple-zookeeper
    image: zookeeper:3.9.2
    restart: always
    networks:
    - test
    environment:
    - ZOO_4LW_COMMANDS_WHITELIST=srvr, ruok
    ports:
    - 10024:2181
    volumes:
    - ./conf/zookeeper:/usr/local/etc/zookeeper
    - ./data/zookeeper:/data
    hostname: zookeeper
    healthcheck:
      test: ["CMD", "sh", "/usr/local/etc/zookeeper/healthcheck_zookeeper.sh"]
      interval: 10s
      start_period: 5s
  hazelcast:
    container_name: exemple-hazelcast
    image: hazelcast/hazelcast:5.4.0
    networks:
    - test
    ports:
     - 5706:5701
    volumes:
    - ./conf/hazelcast:/usr/local/etc/hazelcast
    environment:
    - "JAVA_OPTS=-Dhazelcast.config=/usr/local/etc/hazelcast/hazelcast.yaml"
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "accept:application/json", "http://172.17.0.1:5706/hazelcast/health/ready"]
      interval: 30s
      start_period: 30s
  kafka:
    container_name: exemple-kafka
    image: bitnami/kafka:3.7.1
    networks:
    - test
    ports:
    - 10025:9093
    - 10026:9093
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: 172.17.0.1:10024
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://localhost:9092,EXTERNAL://172.17.0.1:10026
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_ENABLE_KRAFT: "no"
  authorization:
    container_name: exemple-authorization
    image: exemple-authorization
    networks:
    - test
    environment:
    - "CATALINA_OPTS=-Dlogging.config=file:/usr/local/tomcat/etc/logback.xml -Dhazelcast.config=/usr/local/tomcat/etc/hazelcast.yaml -Dhazelcast.client.config=/usr/local/tomcat/etc/hazelcast-client.yaml"
    - "JAVA_OPTS=-Xms256m -Xmx512m -XX:MetaspaceSize=128m"
    - "JPDA_ADDRESS=*:8000"
    - "JPDA_TRANSPORT=dt_socket"
    entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
    ports:
    - 8090:8080
    - 9090:8000
    volumes:
    - ./conf/authorization:/usr/local/tomcat/etc
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "accept:application/json", "http://localhost:8080/ExempleAuthorization/actuator/health"]
      interval: 30s
      start_period: 30s
  service:
    container_name: exemple-service
    image: exemple-service
    networks:
    - test
    environment:
    - "CATALINA_OPTS=-Dlogging.config=file:/usr/local/tomcat/etc/logback.xml -Dhazelcast.client.config=/usr/local/tomcat/etc/hazelcast.yaml"
    - "JAVA_OPTS=-Xms256m -Xmx512m -XX:MetaspaceSize=128m"
    - "JPDA_ADDRESS=8000"
    - "JPDA_TRANSPORT=dt_socket"
    entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
    ports:
    - 8080:8080
    - 5705:5705
    - 9080:8000
    volumes:
    - ./conf/service:/usr/local/tomcat/etc
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "accept:application/json", "http://localhost:8080/ExempleService/actuator/health"]
      interval: 30s
      start_period: 30s
  gateway:
    container_name: exemple-gateway
    image: exemple-gateway
    networks:
    - test
    environment:
    - "--spring.config.location=/usr/local/etc/gateway/exemple-gateway.yml"
    - "--server.servlet.context-path=/"
    - "JAVA_OPTS=-Xms256m -Xmx1g"
    - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
    ports:
    - 8086:8080
    - 9086:8000
    volumes:
    - ./conf/gateway:/usr/local/etc/gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "accept:application/json", "http://localhost:8080/actuator/health"]
      interval: 30s
      start_period: 30s
  ui:
    container_name: exemple-ui
    image: exemple-ui
    networks:
    - test
    ports:
    - 4200:80
networks:
  test:
    name: exemple-test
    driver: bridge
